version: 2

builds:
  - main: ./cmd/telegraf-output-mackerel
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

release:
  github:
    owner: SlashNephy
    name: telegraf-plugins
