before:
  hooks:
    - go mod download

builds:
  - main: ./cmd
    binary: telegraf-output-mackerel
    flags:
      - -trimpath
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm64

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      386: i386
